name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '⚠️ Breaking Changes'
    labels:
      - 'release:major'
  - title: '🚀 Features'
    labels:
      - 'release:minor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'release:patch'
  - title: 'Other Changes'

version-resolver:
  major:
    labels:
      - 'release:major'
  minor:
    labels:
      - 'release:minor'
  patch:
    labels:
      - 'release:patch'

template: |
  $CHANGES

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: '\<*_&'

no-changes-template: 'No notable changes in this release.'
