import { AccordionDefaultableProps } from "../../components/Accordion/types";
import { AlertDefaultableProps } from "../../components/Alert/types";
import { AvatarDefaultableProps } from "../../components/Avatar/types";
import { BadgeDefaultableProps } from "../../components/Badge/types";
import { BreadcrumbDefaultableProps } from "../../components/Breadcrumb/types";
import { BusinessCardDefaultableProps } from "../../components/BusinessCard/types";
import { ButtonDefaultableProps } from "../../components/Button/types";
import { CardDefaultableProps } from "../../components/Card/types";
import { CarouselDefaultableProps } from "../../components/Carousel/types";
import { ButtonGroupProps } from "../../components/ButtonGroup/types";
import { CheckboxDefaultableProps } from "../../components/Checkbox/types";
import { ChipDefaultableProps } from "../../components/Chip/types";
import { DatePickerDefaultableProps } from "../../components/DatePicker/types";
import { DateRangePickerDefaultableProps } from "../../components/DateRangePicker/types";
import { DateTimePickerDefaultableProps } from "../../components/DateTimePicker/types";
import { DataViewDefaultableProps } from "../../components/DataView/types";
import { DividerProps } from "../../components/Divider/types";
import { DropdownDefaultableProps } from "../../components/Dropdown/types";
import { FormDefaultableProps } from "../../components/Form/types";
import { FormFieldGroupDefaultableProps } from "../../components/Form/FormFields/types";
import { GridDefaultableProps } from "../../components/Grid/types";
import { IconProps } from "../../components/Icon/types";
import { IconButtonDefaultableProps } from "../../components/IconButton/types";
import { ImageViewDefaultableProps } from "../../components/ImageView/types";
import { InputDateDefaultableProps } from "../../components/InputDate/types";
import { InputDateRangeDefaultableProps } from "../../components/InputDateRange/types";
import { InputDateTimeDefaultableProps } from "../../components/InputDateTime/types";
import { InputPasswordDefaultableProps } from "../../components/InputPassword/types";
import { InputTextDefaultableProps } from "../../components/InputText/types";
import { InputTimeDefaultableProps } from "../../components/InputTime/types";
import { LinkDefaultableProps } from "../../components/Link/types";
import { ListViewDefaultableProps } from "../../components/ListView/types";
import { MenuListDefaultableProps } from "../../components/MenuList/types";
import { ModalDefaultableProps } from "../../components/Modal/types";
import { NavBarDefaultableProps } from "../../components/NavBar/types";
import { PaginationDefaultableProps } from "../../components/Pagination/types";
import { PanelDefaultableProps } from "../../components/Panel/types";
import { PinCodeDefaultableProps } from "../../components/PinCode/types";
import { PopoverDefaultableProps } from "../../components/Popover/types";
import { ProgressCircleDefaultableProps } from "../../components/ProgressCircle/types";
import { ProgressBarDefaultableProps } from "../../components/ProgressBar/types";
import { RadioDefaultableProps } from "../../components/Radio/types";
import { RadioGroupDefaultableProps } from "../../components/RadioGroup/types";
import { SelectDefaultableProps } from "../../components/Select/types";
import { SliderDefaultableProps } from "../../components/Slider/types";
import { SliderRangeDefaultableProps } from "../../components/SliderRange/types";
// import { SkeletonDefaultableProps } from "../../components/Skeleton/types";
import { StepperDefaultableProps } from "../../components/Stepper/types";
import { SwitchDefaultableProps } from "../../components/Switch/types";
import { TabDefaultableProps } from "../../components/Tab/types";
import { TableDefaultableProps } from "../../components/Table/types";
import { TextDefaultableProps } from "../../components/Text/types";
import { TimelineDefaultableProps } from "../../components/Timeline/types";
import { TextareaDefaultableProps } from "../../components/Textarea/types";
import { TimePickerDefaultableProps } from "../../components/TimePicker/types";
import { ToastDefaultableProps } from "../../components/Toast/types";
import { TooltipDefaultableProps } from "../../components/Tooltip/types";
import { UploadListDefaultableProps } from "../../components/Upload/UploadList/types";
// import { UploadDraggerDefaultableProps } from "../../components/Upload/UploadDragger/types";
import { UploadDefaultableProps } from "../../components/Upload/types";
import { UploadInputDefaultableProps } from "../../components/Upload/UploadInput/types";
import { ImageUploadDefaultableProps } from "../../components/Upload/ImageUpload/types";

export type ComponentDefaultableProps = {
  Accordion?: AccordionDefaultableProps;
  Alert?: AlertDefaultableProps;
  Avatar?: AvatarDefaultableProps;
  Badge?: BadgeDefaultableProps;
  Breadcrumb?: BreadcrumbDefaultableProps;
  BusinessCard?: BusinessCardDefaultableProps;
  Button?: ButtonDefaultableProps;
  ButtonGroup?: ButtonGroupProps;
  Card?: CardDefaultableProps;
  Carousel?: CarouselDefaultableProps;
  Checkbox?: CheckboxDefaultableProps;
  Chip?: ChipDefaultableProps;
  DatePicker?: DatePickerDefaultableProps;
  DateRangePicker?: DateRangePickerDefaultableProps;
  DateTimePicker?: DateTimePickerDefaultableProps;
  DataView?: DataViewDefaultableProps;
  Divider?: DividerProps;
  Dropdown?: DropdownDefaultableProps;
  Form?: FormDefaultableProps;
  FormField?: never;
  FormFieldGroup?: FormFieldGroupDefaultableProps;
  Grid?: GridDefaultableProps;
  Icon?: IconProps;
  IconButton?: IconButtonDefaultableProps;
  ImageView?: ImageViewDefaultableProps;
  ImageUpload?: ImageUploadDefaultableProps;
  InputDate?: InputDateDefaultableProps;
  InputDateRange?: InputDateRangeDefaultableProps;
  InputDateTime?: InputDateTimeDefaultableProps;
  InputPassword?: InputPasswordDefaultableProps;
  InputText?: InputTextDefaultableProps;
  InputTime?: InputTimeDefaultableProps;
  Link?: LinkDefaultableProps;
  ListView?: ListViewDefaultableProps;
  MenuList?: MenuListDefaultableProps;
  Modal?: ModalDefaultableProps;
  NavBar?: NavBarDefaultableProps;
  Pagination?: PaginationDefaultableProps;
  Panel?: PanelDefaultableProps;
  PinCode?: PinCodeDefaultableProps;
  Popover?: PopoverDefaultableProps;
  ProgressCircle?: ProgressCircleDefaultableProps;
  ProgressBar?: ProgressBarDefaultableProps;
  Radio?: RadioDefaultableProps;
  RadioGroup?: RadioGroupDefaultableProps;
  Select?: SelectDefaultableProps;
  Slider?: SliderDefaultableProps;
  SliderRange?: SliderRangeDefaultableProps;
  //  Skeleton?: SkeletonDefaultableProps;
  Stepper?: StepperDefaultableProps;
  Switch?: SwitchDefaultableProps;
  Tab?: TabDefaultableProps;
  Table?: TableDefaultableProps;
  Text?: TextDefaultableProps;
  Textarea?: TextareaDefaultableProps;
  Timeline?: TimelineDefaultableProps;
  TimePicker?: TimePickerDefaultableProps;
  Toast?: ToastDefaultableProps;
  Tooltip?: TooltipDefaultableProps;
  UploadList?: UploadListDefaultableProps;
  UploadDragger?: UploadDefaultableProps;
  UploadInput?: UploadInputDefaultableProps;
};
