name: Auto Label

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: 'false'

      - name: Check core team membership
        id: check_team
        uses: ./.github/actions/check-core-team
        with:
          pr-author: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}

      - name: Apply triage label
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
        env:
          IS_INTERNAL: ${{ steps.check_team.outputs.is-internal }}
        with:
          script: |
            const issueNumber =
              context.payload.pull_request
                ? context.payload.pull_request.number
                : context.payload.issue.number;

            if (process.env.IS_INTERNAL !== 'true') {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                labels: ['needs triage'],
              });
            }
