name: Chromatic UI

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    environment: development
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          persist-credentials: 'false'

      - uses: ./.github/actions/setup-node-deps

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          buildScriptName: 'build:storybook'
          zip: true
          skip: "dependabot/**"