name: UI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout PR head
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'
          persist-credentials: 'false'

      - uses: ./.github/actions/setup-node-deps

      - name: Run Chromatic
        uses: chromaui/action@94713c544284a14195de3b50ef24301579f1877e # v18.0.1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          zip: true
          buildScriptName: "build:storybook"
          skip: "dependabot/**"
          autoAcceptChanges: "main"
          exitOnceUploaded: true