name: Code Validator

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: 'false'

      - name: Setup Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Build Library
        run: npm run build:lib

      - name: Run Linters and Tests
        run: |
          npm run lint
          npm run check:type
          npm run check:scss
          npx jest --ci --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Package size report
        uses: pkg-size/action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=motif-ui
            -Dsonar.projectKey=motif-ui_motifreact
            -Dsonar.sources=src
